docker-library/pypy

- 2/Dockerfile
- 2/slim/Dockerfile
- 3/Dockerfile
- 3/slim/Dockerfile
- update.sh
Ports over roughly the following PRs:
* docker-library/python#121
* docker-library/python#127
* docker-library/python#137
* docker-library/python#139
* docker-library/python#144
Also adds SHA256 checksum checks for the PyPy tarball downloads.
Apologies that this is kind of big but I'm keen that this stuff doesn't get left behind.
> Bring up to equivalent quality as Python images

- .architectures-lib
- 2/Dockerfile
- 3/Dockerfile
- Dockerfile-slim.template
- Dockerfile.template
- generate-stackbrew-library.sh
- release-architectures
- update.sh
PyPy is a little special, and the list of supported architectures sometimes fluctuates over time, so I've adapted the update scripts to take that into account and to vary the output of `generate-stackbrew-library.sh` accordingly.
```diff
$ diff -u <(bashbrew cat pypy) <(bashbrew cat <(./generate-stackbrew-library.sh))--- /dev/fd/63	2017-08-24 16:21:25.818694503 -0700
+++ /dev/fd/62	2017-08-24 16:21:25.819694475 -0700
@@ -2,23 +2,26 @@
GitRepo: https://github.com/docker-library/pypy.git
Tags: 2-5.8.0, 2-5.8, 2-5, 2
-GitCommit: bff939590214797aeb1f5d1c30166edceef2eb6d
+Architectures: amd64, arm32v5, arm32v7, i386
+GitCommit: ae4d6e7d038eb080a55fc3d8d91594505e0f4030
Directory: 2
Tags: 2-5.8.0-slim, 2-5.8-slim, 2-5-slim, 2-slim
-GitCommit: bff939590214797aeb1f5d1c30166edceef2eb6d …
```
> Add support for multiple architectures

- .travis.yml
- 2/onbuild/Dockerfile
- 3/onbuild/Dockerfile
- generate-stackbrew-library.sh
- update.sh
See https://github.com/docker-library/official-images/issues/2076 and https://github.com/docker-library/docs/pull/911.
I figured the recent 5.10.0 release was as good a time as any to finally pull the plug on these.
> Remove all traces of onbuild

- 2/Dockerfile
- 2/slim/Dockerfile
- 3/Dockerfile
- 3/slim/Dockerfile
- Dockerfile-slim.template
- Dockerfile.template
There are other files that could be cleaned up here too (e.g. there's at least one bundled pip in `lib-python`), but this is a start. This doesn't delete `.pyc`/`.pyo` files like in the Python image since PyPy doesn't produce those.
This saves ~15MB of uncompressed image size for PyPy 2 for me.
> Delete Python test files like in Python image

- 2.7/Dockerfile
- 2.7/slim/Dockerfile
- 3.5/Dockerfile
- 3.5/slim/Dockerfile
- 3.6/Dockerfile
- 3.6/slim/Dockerfile
- Dockerfile-slim.template
- Dockerfile.template
- release-architectures
- update.sh
The problematic `.so` file in PyPy3 (that links to old `libssl` releases) can be rebuilt pretty trivially at image build time!
(In PyPy2, the old `libssl` release is linked into `/usr/local/bin/pypy` itself, so there's nothing we can do there short of rebuilding PyPy itself.)
Closes https://github.com/docker-library/pypy/issues/24 (as much as we can)
> Update PyPy 3.x to Debian Stretch

- 2.7/Dockerfile
- 2.7/slim/Dockerfile
- 3.5/Dockerfile
- 3.5/slim/Dockerfile
- 3.6/Dockerfile
- 3.6/slim/Dockerfile
- Dockerfile-slim.template
- Dockerfile.template
- update.sh
Copied from https://github.com/docker-library/python/pull/408
Sync the deletion of pyc/pyo files from python image too!
Slim was moved around to separate pip install layer from pypy layer to match regular version and provide better layer caching on pip updates.
```console
$ docker run --rm pypy:2 find /usr/local -depth \( \( -type d -a \( -name test -o -name tests \) \) -o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \) | wc
595     595   32512
$ docker run --rm pypy:3 find /usr/local -depth \( \( -type d -a \( -name test -o -name tests \) \) -o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \) | wc
700     700   52092
$ docker run --rm pypy:2-slim find /usr/local -depth \( \( -type d -a \( -name test -o -name tests \) \) -o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' …
```
> Check get-pip download

- 2.7/Dockerfile
- 2.7/slim/Dockerfile
- 3.6/Dockerfile
- 3.6/slim/Dockerfile
- Dockerfile-slim.template
- Dockerfile.template
The s390x (and ppc64le) packages updated to also need libexpat1 (on top of libncurses5).
I was hoping this would fix ppc64le too, but it's got an additional segfault in pip:
```console
+ pypy3 get-pip.py --disable-pip-version-check --no-cache-dir pip==20.0.2
Collecting pip==20.0.2
Downloading pip-20.0.2-py2.py3-none-any.whl (1.4 MB)
Collecting setuptools
Downloading setuptools-46.1.3-py3-none-any.whl (582 kB)
Collecting wheel
Downloading wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: pip, setuptools, wheel
Segmentation fault (core dumped)
```
> Fix s390x builds

- 2.7/Dockerfile
- 2.7/slim/Dockerfile
- 3.6/Dockerfile
- 3.6/slim/Dockerfile
- Dockerfile-slim.template
- Dockerfile.template
- update.sh
This follows upstream's recommendations more closely, and should remove the `ldconfig` warnings we see during certain `apt-get`/`dpkg` operations.
Also, this switches to using https://downloads.python.org/pypy/, which is supposed to be the canonical upstream download location.
Refs #35, especially https://github.com/docker-library/pypy/issues/35#issuecomment-644179330
> Move from "/usr/local" to "/opt/pypy"

- 2.7/Dockerfile
- 2.7/slim/Dockerfile
- 3.6/Dockerfile
- 3.6/slim/Dockerfile
- 3.7/Dockerfile
- 3.7/slim/Dockerfile
- update.sh
I'm not 100% sure this is the "right" solution, but we have the very real situation where pip 21.x has been released which drops Python 2 support, but PyPy is still actively supporting their Python 2 variant (for the foreseeable future), and IMO it would be strange for us to ship pip 21.x for `pypy:3` and pip 20.x for `pypy:2` when they're actually part of the same PyPy release (not separate release lines, like in upstream Python).
> Pin pip to 20.x (the last version to support Python 2)

- 2.7/slim-buster/Dockerfile
- 3.6/buster/Dockerfile
- 3.6/slim-buster/Dockerfile
- 3.7/buster/Dockerfile
- 3.7/slim-buster/Dockerfile
- Dockerfile-linux.template
> Apply thread-related crypt patches in 3.x versions

- 2.7/windows/windowsservercore-1809/Dockerfile
- 3.6/windows/windowsservercore-1809/Dockerfile
- 3.7/windows/windowsservercore-1809/Dockerfile
- Dockerfile-linux.template
- Dockerfile-windows-servercore.template
- apply-templates.sh
- generate-stackbrew-library.sh
- versions.json
- versions.sh
This expands on #53 with some initial support for building on Windows (so it can be tested).
> Add initial Windows variants

- generate-stackbrew-library.sh
> `pypy3: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory`
<details>
<summary>Diff:</summary>
```diff
$ diff -u <(bashbrew cat pypy) <(bashbrew cat <(./generate-stackbrew-library.sh))
--- /dev/fd/63	2021-08-20 11:29:32.119968516 -0700
+++ /dev/fd/62	2021-08-20 11:29:32.119968516 -0700
@@ -3,12 +3,12 @@
Tags: 3.7-7.3.5-bullseye, 3.7-7.3-bullseye, 3.7-7-bullseye, 3.7-bullseye, 3-7.3.5-bullseye, 3-7.3-bullseye, 3-7-bullseye, 3-bullseye, bullseye
SharedTags: 3.7-7.3.5, 3.7-7.3, 3.7-7, 3.7, 3-7.3.5, 3-7.3, 3-7, 3, latest
-Architectures: amd64, arm64v8, i386, s390x
+Architectures: amd64, arm64v8, i386
GitCommit: 2c7223f5fc2fba18bc8e5cb14896668a5c330ae1
Directory: 3.7/bullseye
Tags: 3.7-7.3.5-slim, 3.7-7.3-slim, 3.7-7-slim, 3.7-slim, …
```
> Exclude "s390x" for bullseye+ (due to libffi6 vs libffi7)

- 2.7/bullseye/Dockerfile
- 2.7/buster/Dockerfile
- 2.7/slim-bullseye/Dockerfile
- 2.7/slim-buster/Dockerfile
- 2.7/windows/windowsservercore-1809/Dockerfile
- 3.7/bullseye/Dockerfile
- 3.7/buster/Dockerfile
- 3.7/slim-bullseye/Dockerfile
- 3.7/slim-buster/Dockerfile
- 3.7/windows/windowsservercore-1809/Dockerfile
- Dockerfile-linux.template
- Dockerfile-windows-servercore.template
- versions.json
- versions.sh
See https://github.com/docker-library/python/pull/647, https://github.com/docker-library/python/issues/365
> Pin setuptools to 44.x

- 2.7/bullseye/Dockerfile
- 2.7/buster/Dockerfile
- 2.7/slim-bullseye/Dockerfile
- 2.7/slim-buster/Dockerfile
- 2.7/windows/windowsservercore-1809/Dockerfile
- 3.7/bullseye/Dockerfile
- 3.7/buster/Dockerfile
- 3.7/slim-bullseye/Dockerfile
- 3.7/slim-buster/Dockerfile
- 3.7/windows/windowsservercore-1809/Dockerfile
- Dockerfile-linux.template
- Dockerfile-windows-servercore.template
- versions.json
- versions.sh
This is essentially https://github.com/docker-library/python/pull/647, but pulling directly from the `ensurepip` module instead of scraping it in `versions.sh`.
The only bit I'm not sure about is whether we need a newer `get-pip.py` commit that matches the version of PIP being used.
This is a replacement for #61, and closes #62.
> Scrape PIP and setuptools versions directly from "ensurepip"

- generate-stackbrew-library.sh
PyPy now seems to consider 3.8 a stable release (looking at the table of contents): https://doc.pypy.org/en/latest/release-v7.3.7.html
This would mean that the tag for '3' and therefore 'latest' can be moved to '3.8'.
Related to #65
> Move the tags for '3' and 'latest'

- generate-stackbrew-library.sh
On many builds, we get:
> `pypy3: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory`
Which we can't resolve on Bullseye+ (same as s390x).
On others, we get:
> `pypy: error while loading shared libraries: libtinfow.so.6: cannot open shared object file: No such file or directory`
Which appears to be a CentOS-specific library name and I couldn't convince `pypy` to be satisfied by any symlinks to either `libtinfo` or `libtic` (which were the suggestions I found on other projects for fixing similar linking issues).
See also https://github.com/docker-library/pypy/pull/58 (for where we removed `s390x` bullseye builds).
<details>
<summary>Diff:</summary>
```diff
$ diff -u <(bashbrew cat pypy) <(bashbrew cat …
```
> Remove arm64v8

- 2.7/bullseye/Dockerfile
- 2.7/buster/Dockerfile
- 2.7/slim-bullseye/Dockerfile
- 2.7/slim-buster/Dockerfile
- 2.7/windows/windowsservercore-1809/Dockerfile
- 3.7/bullseye/Dockerfile
- 3.7/buster/Dockerfile
- 3.7/slim-bullseye/Dockerfile
- 3.7/slim-buster/Dockerfile
- 3.7/windows/windowsservercore-1809/Dockerfile
- 3.8/bullseye/Dockerfile
- 3.8/buster/Dockerfile
- 3.8/slim-bullseye/Dockerfile
- 3.8/slim-buster/Dockerfile
- 3.8/windows/windowsservercore-1809/Dockerfile
- 3.9/bullseye/Dockerfile
- 3.9/buster/Dockerfile
- 3.9/slim-bullseye/Dockerfile
- 3.9/slim-buster/Dockerfile
- 3.9/windows/windowsservercore-1809/Dockerfile
- Dockerfile-linux.template
- Dockerfile-windows-servercore.template
- generate-stackbrew-library.sh
- versions.json
- versions.sh
Getting version/URL information from https://downloads.python.org/pypy/versions.json should give us much more accurate and reliable versioning information than scraping HTML does.
This _also_ gets us the correct adjusted URL for the current `aarch64` releases that allow us to bring back `arm64v8` support! (https://github.com/docker-library/pypy/pull/69#issuecomment-1061057221) :tada:
Thanks @mattip!!
> Switch to using the upstream-provided "versions.json" file

- Dockerfile-windows-servercore.template
The end result is the same, but the construction is more ergonomic ( :trollface: ).
See also https://github.com/docker-library/buildpack-deps/pull/165 (and linked)
> Use jq's `IN()` instead of `index()`

- 2.7/windows/windowsservercore-ltsc2025/Dockerfile
- 3.10/windows/windowsservercore-ltsc2025/Dockerfile
- versions.json
- versions.sh
Add Windows Server ltsc2025; keep 1809 as it is still in extended support (we may drop it later, even while it is supported by Windows).
Refs: https://github.com/docker-library/official-images/pull/18143
> Add Windows Server 2025 variant

- 3.11/bookworm/Dockerfile
- 3.11/slim-bookworm/Dockerfile
- 3.11/windows/windowsservercore-1809/Dockerfile
- 3.11/windows/windowsservercore-ltsc2022/Dockerfile
- 3.11/windows/windowsservercore-ltsc2025/Dockerfile
- versions.json
- versions.sh
:eyes: https://www.pypy.org/posts/2025/02/pypy-v7318-release.html
(still considered "beta", so I've left "3" and "latest" pointing to 3.10)
> Add the 3.11 beta builds too

- generate-stackbrew-library.sh
We should've done this back in https://github.com/docker-library/pypy/pull/77 (9a9efe06150ce464f288617c8e3ec765bb93250e), but missed it. 🙈
> Update generic/default aliases to bookworm

- 2.7/bookworm/Dockerfile
- 2.7/bullseye/Dockerfile
- 2.7/slim-bookworm/Dockerfile
- 2.7/slim-bullseye/Dockerfile
- 2.7/windows/windowsservercore-1809/Dockerfile
- 2.7/windows/windowsservercore-ltsc2022/Dockerfile
- 2.7/windows/windowsservercore-ltsc2025/Dockerfile
- 3.10/bookworm/Dockerfile
- 3.10/bullseye/Dockerfile
- 3.10/slim-bookworm/Dockerfile
- 3.10/slim-bullseye/Dockerfile
- 3.10/windows/windowsservercore-1809/Dockerfile
- 3.10/windows/windowsservercore-ltsc2022/Dockerfile
- 3.10/windows/windowsservercore-ltsc2025/Dockerfile
- 3.11/bookworm/Dockerfile
- 3.11/slim-bookworm/Dockerfile
- 3.11/windows/windowsservercore-1809/Dockerfile
- 3.11/windows/windowsservercore-ltsc2022/Dockerfile
- 3.11/windows/windowsservercore-ltsc2025/Dockerfile
- Dockerfile-linux.template
- Dockerfile-windows-servercore.template
- shared.jq
Instead of asking `ensurepip` which version of `pip` (and `setuptools`) to install via `get-pip.py`, just ask `ensurepip` to install them.
> Swap from explicit `get-pip.py` to `ensurepip`
